### DISCUSSION TITLE
Configuration questions

### DISCUSSION THREAD

**Discussion by myriaxis** [hassio-addons/app-nut#240] [General]
# Problem/Motivation

Would like to clarify the HA NUT add-on configuration.

## Expected behavior

Hope to get answers to my questions...

## Actual behavior

My setup is HA running on Raspberry Pi powered by a CyberPower UPS.
I installed the HA NUT add-on to monitor the UPS.
I'm also using HA to update UDI ISY state variables.
I managed quickly to make it work with this config:
```
devices:
  - config: []
    driver: usbhid-ups
    name: CP1350AVR
    port: auto
mode: netserver
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    username: xxxxxx
    password: xxxxxx
i_like_to_be_pwned: false
list_usb_devices: true
```
During my testing, I noticed that the delay between a UPS event and the ISY state variables update is fairly long.
So, I started looking into POLLINTERVAL and POLLFREQ options for upsmon.
From the documentation I found, it seems that:
POLLINTERVAL is set to 2 seconds by default.
POLLFREQ is set to 30 seconds by default.

**1st question:** What are the values for POLLINTERVAL and POLLFREQ in the add-on?
**2nd question:** Can we modify them? If yes, how?
I tried to add the POLLFREQ option to the add-on.
Here is what I tried:
```
devices:
  - name: CP1350AVR
    driver: usbhid-ups
    port: auto
    config:
      - pollfreq = 5
```
Does it work like that?

## Steps to reproduce

N/A

## Proposed changes

N/A

**Comment by sinclairpaul** [comment]
If it isn't listed in the documentation and isn't part of the device config, it cannot be changed and will be the defaults.

I assume you are using the HA integration to look at state changes, which is local polling, so may take some time to update.  The addon also fires events on UPS state changes, which are likely to be quicker, the details are listed in the documentation.

**Comment by myriaxis** [comment]
Thanks @sinclairpaul,
Sorry for posting in the wrong section of the forum.

If I understand correctly, the HA NUT integration, client side, will poll the server side, the NUT add-on, at the specified "scan interval" as specified in the HA NUT integration Configure/Option pop-up. Apparently, the scan interval can be between 10 and 300 seconds. I set it to 10 seconds which is fine for my HA dashboard update.

On the other hand, I have a HA script that runs every 5 seconds to transfer the UPS status (values from the NUT add-on) to my ISY via state variables. If the NUT add-on refresh rate is more than 5 seconds, then it will impact the time it takes for my ISY to react. That's why I want to know the default values of POLLINTERVAL and POLLFREQ, and how to modify them in the NUT add-on.

From the NUT add-on [documentation page](https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md), under the option "devices", there is a reference link to [ups.conf(5)](https://networkupstools.org/docs/man/ups.conf.html) where you find that POLLINTERVAL is optional and normally set to 2 seconds. As this option been specified in the NUT add-on? If yes, which default value has it been set to? Is it hardcoded or can we specify a new value in the add-on configuration?
Also on the NUT add-on documentation page, under the suboption "devices/config", there is a reference link to [usbhid-ups driver](https://networkupstools.org/docs/man/usbhid-ups.html) where you find that POLLFREQ has a default value of 30 seconds, which is way too much. As this option been specified in the NUT add-on? If yes, which default value has it been set to? Is it hardcoded or can we specify a new value in the add-on configuration?

POLLINTERVAL and POLLFREQ are genuine Network UPS Tools configuration variables. I just want to know if these have been implemented in the HA NUT add-on project.

**Reply by sinclairpaul** [reply]
Anything specified under the devices options will be written to the ups.conf file as you can see at <https://github.com/hassio-addons/addon-nut/blob/main/nut/rootfs/etc/cont-init.d/nut.sh#L94>

pollfreq looks to be a driver option, and would therefore be set to the default.

**Comment by myriaxis** [comment]
Thank you,
From what I can tell, the driver also reads from ups.conf. So, as you stated, if I specify the variables like this:
```
- name: CP1350AVR
  driver: usbhid-ups
  port: auto
  config:
    - pollinterval = 2
    - pollfreq = 5
```
Both variables should be passed on.
Correct?
