### DISCUSSION TITLE
"Fatal error: insufficient power configured!" + "powervalue: 1" not working

### DISCUSSION THREAD

**Discussion by majoo23** [hassio-addons/app-nut#355] [Q&A]
I have an NUT NetworkServer (as Master) on a Synology NAS, that is connected via USB to a CyberPower VP1000ELCD UPS. 

An Unraid Server uses the Unraid NUT Plugin to read that UPS Server(synology) as a slave, which works smoothly. 

Now, I want to receive notifications via Homeassistant (hosted on the Unraid server) in case of a power outage. I installed the NUT AddOn on Homeassistant but encountered issues:

The NUT AddOn runs as a slave/network client, successfully authenticates with the NutServer (Synology NAS), but then crashes with the following error message:

```
Network UPS Tools upsmon 2.8.0

Fatal error: insufficient power configured!

Sum of power values........: 0
Minimum value (MINSUPPLIES): 1

Edit your upsmon.conf and adjust the values.
[15:25:09] WARNING: upsmon crashed, halting add-on
[15:25:09] INFO: upsmon stopped, restarting...
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
[15:25:10] INFO: upsmon stopped, restarting...
[15:25:10] INFO: upsd stopped, restarting...
```

Even after adding "`powervalue: 1`" to the YAML file as suggested in the wiki, the issue persists. 
And what does `Edit your upsmon.conf and change the values.` mean ?  i dont get it :/ i added the powervalue line to the yaml

 It seems to be more challenging on Homeassistant compared to Unraid. 

Any suggestions or help would be greatly appreciated.

Here is my NUT config as code and the log as a pic:

```
users:
  - username: ""
    password: ""
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
    powervalue: 1
mode: netclient
shutdown_host: false
remote_ups_host: 192.168.0.3
remote_ups_name: ups
i_like_to_be_pwned: true
remote_ups_user: ""
remote_ups_password: ""
```

![2024-04-06_15h25_25](https://github.com/hassio-addons/addon-nut/assets/131711049/2efd0ad3-59c6-4924-9c68-eb02124287d8)
