### DISCUSSION TITLE
How to disable automatic addon shutdown?

### DISCUSSION THREAD

**Discussion by shalak** [hassio-addons/app-nut#378] [Q&A]
I monitor UPS that is not even connected to the host I run Home Assistant on. I'm using HassOS installation on a VM.

When UPS entered power failure state, the addon shut itself down (it didn't shut Home Assistant itself)

My configuration looks like this:

```
users:
  - username: nut
    password: !secret nut_pass
    instcmds:
      - all
    actions: []
devices:
  - name: ups-serwerownia
    driver: snmp-ups
    port: 10.0.0.51
    snmp_version: v3
    secLevel: authPriv
    authProtocol: SHA
    authPassword: !secret ups_pass
    privProtocol: AES
    privPassword: !secret ups_pass
    desc: UPS APC SMART SUA3000RMI 2U AP9619
    config: []
mode: netserver
shutdown_host: "false"
```

That begs two questions:

How do I prevent automatic addon shutdown?

Isn't addon supposed to shutdown Home Assistant itself?
